// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.3
// source: coordinate_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GossipCoordinate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []float64              `protobuf:"fixed64,1,rep,packed,name=Value,proto3" json:"Value,omitempty"` // list of coordinates
	Node  *Node                  `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Time  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *GossipCoordinate) Reset() {
	*x = GossipCoordinate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordinate_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GossipCoordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipCoordinate) ProtoMessage() {}

func (x *GossipCoordinate) ProtoReflect() protoreflect.Message {
	mi := &file_coordinate_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipCoordinate.ProtoReflect.Descriptor instead.
func (*GossipCoordinate) Descriptor() ([]byte, []int) {
	return file_coordinate_message_proto_rawDescGZIP(), []int{0}
}

func (x *GossipCoordinate) GetValue() []float64 {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GossipCoordinate) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *GossipCoordinate) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type GossipCoordinateList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coordinates []*GossipCoordinate `protobuf:"bytes,1,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
}

func (x *GossipCoordinateList) Reset() {
	*x = GossipCoordinateList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordinate_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GossipCoordinateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipCoordinateList) ProtoMessage() {}

func (x *GossipCoordinateList) ProtoReflect() protoreflect.Message {
	mi := &file_coordinate_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipCoordinateList.ProtoReflect.Descriptor instead.
func (*GossipCoordinateList) Descriptor() ([]byte, []int) {
	return file_coordinate_message_proto_rawDescGZIP(), []int{1}
}

func (x *GossipCoordinateList) GetCoordinates() []*GossipCoordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

var File_coordinate_message_proto protoreflect.FileDescriptor

var file_coordinate_message_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x12, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x79, 0x0a, 0x10, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70,
	0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x1f, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64,
	0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x22, 0x51, 0x0a, 0x14, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x43, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x0b, 0x63, 0x6f, 0x6f,
	0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x43, 0x6f, 0x6f,
	0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_coordinate_message_proto_rawDescOnce sync.Once
	file_coordinate_message_proto_rawDescData = file_coordinate_message_proto_rawDesc
)

func file_coordinate_message_proto_rawDescGZIP() []byte {
	file_coordinate_message_proto_rawDescOnce.Do(func() {
		file_coordinate_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_coordinate_message_proto_rawDescData)
	})
	return file_coordinate_message_proto_rawDescData
}

var file_coordinate_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_coordinate_message_proto_goTypes = []any{
	(*GossipCoordinate)(nil),      // 0: proto.GossipCoordinate
	(*GossipCoordinateList)(nil),  // 1: proto.GossipCoordinateList
	(*Node)(nil),                  // 2: proto.Node
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_coordinate_message_proto_depIdxs = []int32{
	2, // 0: proto.GossipCoordinate.node:type_name -> proto.Node
	3, // 1: proto.GossipCoordinate.time:type_name -> google.protobuf.Timestamp
	0, // 2: proto.GossipCoordinateList.coordinates:type_name -> proto.GossipCoordinate
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_coordinate_message_proto_init() }
func file_coordinate_message_proto_init() {
	if File_coordinate_message_proto != nil {
		return
	}
	file_node_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_coordinate_message_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GossipCoordinate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordinate_message_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GossipCoordinateList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_coordinate_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coordinate_message_proto_goTypes,
		DependencyIndexes: file_coordinate_message_proto_depIdxs,
		MessageInfos:      file_coordinate_message_proto_msgTypes,
	}.Build()
	File_coordinate_message_proto = out.File
	file_coordinate_message_proto_rawDesc = nil
	file_coordinate_message_proto_goTypes = nil
	file_coordinate_message_proto_depIdxs = nil
}
