// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.3
// source: node_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	MembershipIp   string `protobuf:"bytes,2,opt,name=MembershipIp,proto3" json:"MembershipIp,omitempty"`
	MembershipPort uint32 `protobuf:"varint,3,opt,name=MembershipPort,proto3" json:"MembershipPort,omitempty"`
	VivaldiIp      string `protobuf:"bytes,4,opt,name=VivaldiIp,proto3" json:"VivaldiIp,omitempty"`
	VivaldiPort    uint32 `protobuf:"varint,5,opt,name=VivaldiPort,proto3" json:"VivaldiPort,omitempty"`
	GossipIp       string `protobuf:"bytes,6,opt,name=GossipIp,proto3" json:"GossipIp,omitempty"`
	GossipPort     uint32 `protobuf:"varint,7,opt,name=GossipPort,proto3" json:"GossipPort,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_node_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_node_message_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetMembershipIp() string {
	if x != nil {
		return x.MembershipIp
	}
	return ""
}

func (x *Node) GetMembershipPort() uint32 {
	if x != nil {
		return x.MembershipPort
	}
	return 0
}

func (x *Node) GetVivaldiIp() string {
	if x != nil {
		return x.VivaldiIp
	}
	return ""
}

func (x *Node) GetVivaldiPort() uint32 {
	if x != nil {
		return x.VivaldiPort
	}
	return 0
}

func (x *Node) GetGossipIp() string {
	if x != nil {
		return x.GossipIp
	}
	return ""
}

func (x *Node) GetGossipPort() uint32 {
	if x != nil {
		return x.GossipPort
	}
	return 0
}

type NodeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*Node `protobuf:"bytes,1,rep,name=Nodes,proto3" json:"Nodes,omitempty"` // list of nodes
}

func (x *NodeList) Reset() {
	*x = NodeList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeList) ProtoMessage() {}

func (x *NodeList) ProtoReflect() protoreflect.Message {
	mi := &file_node_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeList.ProtoReflect.Descriptor instead.
func (*NodeList) Descriptor() ([]byte, []int) {
	return file_node_message_proto_rawDescGZIP(), []int{1}
}

func (x *NodeList) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_node_message_proto protoreflect.FileDescriptor

var file_node_message_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xde, 0x01, 0x0a, 0x04,
	0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68,
	0x69, 0x70, 0x49, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x49, 0x70, 0x12, 0x26, 0x0a, 0x0e, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x50, 0x6f, 0x72, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x56, 0x69, 0x76, 0x61, 0x6c, 0x64, 0x69, 0x49, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x56, 0x69, 0x76, 0x61, 0x6c, 0x64, 0x69, 0x49, 0x70, 0x12, 0x20,
	0x0a, 0x0b, 0x56, 0x69, 0x76, 0x61, 0x6c, 0x64, 0x69, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0b, 0x56, 0x69, 0x76, 0x61, 0x6c, 0x64, 0x69, 0x50, 0x6f, 0x72, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x49, 0x70, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x49, 0x70, 0x12, 0x1e, 0x0a, 0x0a,
	0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x2d, 0x0a, 0x08,
	0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x05, 0x4e, 0x6f, 0x64, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_node_message_proto_rawDescOnce sync.Once
	file_node_message_proto_rawDescData = file_node_message_proto_rawDesc
)

func file_node_message_proto_rawDescGZIP() []byte {
	file_node_message_proto_rawDescOnce.Do(func() {
		file_node_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_node_message_proto_rawDescData)
	})
	return file_node_message_proto_rawDescData
}

var file_node_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_node_message_proto_goTypes = []any{
	(*Node)(nil),     // 0: proto.Node
	(*NodeList)(nil), // 1: proto.NodeList
}
var file_node_message_proto_depIdxs = []int32{
	0, // 0: proto.NodeList.Nodes:type_name -> proto.Node
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_node_message_proto_init() }
func file_node_message_proto_init() {
	if File_node_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_node_message_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_message_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*NodeList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_node_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_message_proto_goTypes,
		DependencyIndexes: file_node_message_proto_depIdxs,
		MessageInfos:      file_node_message_proto_msgTypes,
	}.Build()
	File_node_message_proto = out.File
	file_node_message_proto_rawDesc = nil
	file_node_message_proto_goTypes = nil
	file_node_message_proto_depIdxs = nil
}
