// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: vivaldi_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Vivaldi_PullCoordinates_FullMethodName = "/proto.Vivaldi/PullCoordinates"
)

// VivaldiClient is the client API for Vivaldi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Has to be a pull model since the client got the server in its partial view and not vice versa
type VivaldiClient interface {
	PullCoordinates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VivaldiCoordinate, error)
}

type vivaldiClient struct {
	cc grpc.ClientConnInterface
}

func NewVivaldiClient(cc grpc.ClientConnInterface) VivaldiClient {
	return &vivaldiClient{cc}
}

func (c *vivaldiClient) PullCoordinates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VivaldiCoordinate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VivaldiCoordinate)
	err := c.cc.Invoke(ctx, Vivaldi_PullCoordinates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VivaldiServer is the server API for Vivaldi service.
// All implementations must embed UnimplementedVivaldiServer
// for forward compatibility.
//
// Has to be a pull model since the client got the server in its partial view and not vice versa
type VivaldiServer interface {
	PullCoordinates(context.Context, *Empty) (*VivaldiCoordinate, error)
	mustEmbedUnimplementedVivaldiServer()
}

// UnimplementedVivaldiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVivaldiServer struct{}

func (UnimplementedVivaldiServer) PullCoordinates(context.Context, *Empty) (*VivaldiCoordinate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullCoordinates not implemented")
}
func (UnimplementedVivaldiServer) mustEmbedUnimplementedVivaldiServer() {}
func (UnimplementedVivaldiServer) testEmbeddedByValue()                 {}

// UnsafeVivaldiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VivaldiServer will
// result in compilation errors.
type UnsafeVivaldiServer interface {
	mustEmbedUnimplementedVivaldiServer()
}

func RegisterVivaldiServer(s grpc.ServiceRegistrar, srv VivaldiServer) {
	// If the following call pancis, it indicates UnimplementedVivaldiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Vivaldi_ServiceDesc, srv)
}

func _Vivaldi_PullCoordinates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VivaldiServer).PullCoordinates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vivaldi_PullCoordinates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VivaldiServer).PullCoordinates(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Vivaldi_ServiceDesc is the grpc.ServiceDesc for Vivaldi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Vivaldi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Vivaldi",
	HandlerType: (*VivaldiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PullCoordinates",
			Handler:    _Vivaldi_PullCoordinates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vivaldi_service.proto",
}
