// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: vivaldi_gossip_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VivaldiGossip_Gossip_FullMethodName = "/proto.VivaldiGossip/Gossip"
)

// VivaldiGossipClient is the client API for VivaldiGossip service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VivaldiGossipClient interface {
	Gossip(ctx context.Context, in *GossipCoordinateList, opts ...grpc.CallOption) (*GossipCoordinateList, error)
}

type vivaldiGossipClient struct {
	cc grpc.ClientConnInterface
}

func NewVivaldiGossipClient(cc grpc.ClientConnInterface) VivaldiGossipClient {
	return &vivaldiGossipClient{cc}
}

func (c *vivaldiGossipClient) Gossip(ctx context.Context, in *GossipCoordinateList, opts ...grpc.CallOption) (*GossipCoordinateList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GossipCoordinateList)
	err := c.cc.Invoke(ctx, VivaldiGossip_Gossip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VivaldiGossipServer is the server API for VivaldiGossip service.
// All implementations must embed UnimplementedVivaldiGossipServer
// for forward compatibility.
type VivaldiGossipServer interface {
	Gossip(context.Context, *GossipCoordinateList) (*GossipCoordinateList, error)
	mustEmbedUnimplementedVivaldiGossipServer()
}

// UnimplementedVivaldiGossipServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVivaldiGossipServer struct{}

func (UnimplementedVivaldiGossipServer) Gossip(context.Context, *GossipCoordinateList) (*GossipCoordinateList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Gossip not implemented")
}
func (UnimplementedVivaldiGossipServer) mustEmbedUnimplementedVivaldiGossipServer() {}
func (UnimplementedVivaldiGossipServer) testEmbeddedByValue()                       {}

// UnsafeVivaldiGossipServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VivaldiGossipServer will
// result in compilation errors.
type UnsafeVivaldiGossipServer interface {
	mustEmbedUnimplementedVivaldiGossipServer()
}

func RegisterVivaldiGossipServer(s grpc.ServiceRegistrar, srv VivaldiGossipServer) {
	// If the following call pancis, it indicates UnimplementedVivaldiGossipServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VivaldiGossip_ServiceDesc, srv)
}

func _VivaldiGossip_Gossip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipCoordinateList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VivaldiGossipServer).Gossip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VivaldiGossip_Gossip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VivaldiGossipServer).Gossip(ctx, req.(*GossipCoordinateList))
	}
	return interceptor(ctx, in, info, handler)
}

// VivaldiGossip_ServiceDesc is the grpc.ServiceDesc for VivaldiGossip service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VivaldiGossip_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.VivaldiGossip",
	HandlerType: (*VivaldiGossipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Gossip",
			Handler:    _VivaldiGossip_Gossip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vivaldi_gossip_service.proto",
}
